# Netlify configuration file
# Next.js + Netlify Functions 用
[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = "netlify-functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  TYPESCRIPT_ENABLED = "true"

[dev]
  command = "npm run dev"
  port = 3000

# Next.js API Routes を Netlify Functions にリダイレクト
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA用のフォールバック（Next.jsの動的ルーティング対応）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 